import os
import re
import glob
from collections import defaultdict
import requests

# Configuration
LOG_DIR = "./logs"
REPORT_DIR = "./reports"
OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.1:latest"
BRUTE_FORCE_THRESHOLD = 5  # Failed attempts from same IP to trigger brute force alert

def parse_logs(file_path):
    """
    Parses SSH/Auth log files to extract failed logins and vulnerability indicators.
    """
    failed_ips = defaultdict(int)
    suspicious_lines = []
    
    # Regex patterns for SSH logs and common web attack payloads
    ip_pattern = r"(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
    failed_pattern = r"(Failed password|authentication failure|Invalid user)"
    exploit_pattern = r"(UNION SELECT|<script>|\.\./|etc/passwd|eval\(|\$\{jndi:)"

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            # 1. Detect Brute Force attempts
            if re.search(failed_pattern, line, re.IGNORECASE):
                match = re.search(ip_pattern, line)
                if match:
                    ip = match.group(1)
                    failed_ips[ip] += 1
            
            # 2. Detect Generic Web/Vulnerability Scanning signatures
            if re.search(exploit_pattern, line, re.IGNORECASE):
                suspicious_lines.append(line.strip())

    # Filter IPs exceeding threshold
    brute_force_detected = {ip: count for ip, count in failed_ips.items() if count >= BRUTE_FORCE_THRESHOLD}
    
    return brute_force_detected, suspicious_lines

def analyze_with_local_llm(brute_force_data, suspicious_lines):
    """
    Passes pre-filtered security telemetry to the local Ollama LLM for reasoning.
    """
    prompt = f"""
    You are an expert Cybersecurity Incident Response AI Agent.
    Analyze the following structured log summary and generate a detailed Security Incident Report.

    --- DATA SUMMARY ---
    Brute Force Indicators (IP: Failed Attempts):
    {brute_force_data if brute_force_data else "None detected"}

    Suspicious Payload/Vulnerability Signatures Found:
    {suspicious_lines[:15] if suspicious_lines else "None detected"}
    --- END DATA SUMMARY ---

    Your response must include:
    1. Executive Summary: High-level overview of findings.
    2. Brute Force Analysis: Identified malicious IPs, risk level, and potential impact.
    3. Potential Vulnerability Exploits: Analysis of suspicious log payloads.
    4. Mitigation Steps: Specific actionable recommendations (e.g., fail2ban, IP blocking, firewall rules).
    """

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(OLLAMA_URL, json=payload)
        response.raise_for_status()
        return response.json().get("response", "No response generated by LLM.")
    except Exception as e:
        return f"Error communicating with local LLM: {str(e)}"

def run_agent():
    os.makedirs(REPORT_DIR, exist_ok=True)
    log_files = glob.glob(os.path.join(LOG_DIR, "*.log")) + glob.glob(os.path.join(LOG_DIR, "*.txt"))

    if not log_files:
        print(f"No log files found in '{LOG_DIR}' directory.")
        return

    for log_path in log_files:
        filename = os.path.basename(log_path)
        print(f"[*] Analyzing log file: {filename}...")
        
        # Phase 1: Deterministic Analysis
        brute_force_data, suspicious_lines = parse_logs(log_path)
        
        # Phase 2: LLM Threat Synthesis
        print("[*] Generating threat intelligence report via Local LLM...")
        report_content = analyze_with_local_llm(brute_force_data, suspicious_lines)
        
        # Phase 3: Save Report
        report_filename = f"report_{os.path.splitext(filename)[0]}.md"
        report_path = os.path.join(REPORT_DIR, report_filename)
        
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        print(f"[+] Report generated successfully: {report_path}\n")

if __name__ == "__main__":
    run_agent()
